// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportClientStats():Promise<string>;

export function ExportNetworks(arg1:string):Promise<string>;

export function GetAPPlacementRecommendations():Promise<Array<string>>;

export function GetAvailableInterfaces():Promise<Array<string>>;

export function GetChannelAnalysis():Promise<Array<main.ChannelInfo>>;

export function GetClientStats():Promise<main.ClientStats>;

export function GetNetworks():Promise<Array<main.Network>>;

export function GetRoamingAnalysis():Promise<Record<string, any>>;

export function IsScanning():Promise<boolean>;

export function StartScanning(arg1:string):Promise<void>;

export function StopScanning():Promise<void>;
