// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportClientStats():Promise<string>;

export function ExportNetworks(arg1:string):Promise<string>;

export function GetAPPlacementRecommendations():Promise<Array<string>>;

export function GetAPSignalHistory():Promise<Array<main.APSignalHistory>>;

export function GetAvailableInterfaces():Promise<Array<string>>;

export function GetChannelAnalysis():Promise<Array<main.ChannelInfo>>;

export function GetClientStats():Promise<main.ClientStats>;

export function GetConfig():Promise<main.Config>;

export function GetLatency():Promise<Array<main.LatencyTargetSummary>>;

export function GetNetworks():Promise<Array<main.Network>>;

export function GetRoamingAnalysis():Promise<main.RoamingQualityReport>;

export function IsScanning():Promise<boolean>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveReport(arg1:string,arg2:string):Promise<string>;

export function StartScanning(arg1:string):Promise<void>;

export function StopScanning():Promise<void>;
