// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportClientStats() {
  return window['go']['main']['App']['ExportClientStats']();
}

export function ExportNetworks(arg1) {
  return window['go']['main']['App']['ExportNetworks'](arg1);
}

export function GetAPPlacementRecommendations() {
  return window['go']['main']['App']['GetAPPlacementRecommendations']();
}

export function GetAPSignalHistory() {
  return window['go']['main']['App']['GetAPSignalHistory']();
}

export function GetAvailableInterfaces() {
  return window['go']['main']['App']['GetAvailableInterfaces']();
}

export function GetChannelAnalysis() {
  return window['go']['main']['App']['GetChannelAnalysis']();
}

export function GetClientStats() {
  return window['go']['main']['App']['GetClientStats']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLatency() {
  return window['go']['main']['App']['GetLatency']();
}

export function GetNetworks() {
  return window['go']['main']['App']['GetNetworks']();
}

export function GetRoamingAnalysis() {
  return window['go']['main']['App']['GetRoamingAnalysis']();
}

export function IsScanning() {
  return window['go']['main']['App']['IsScanning']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveReport(arg1, arg2) {
  return window['go']['main']['App']['SaveReport'](arg1, arg2);
}

export function StartScanning(arg1) {
  return window['go']['main']['App']['StartScanning'](arg1);
}

export function StopScanning() {
  return window['go']['main']['App']['StopScanning']();
}
